// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9aC2YF9KBCkFptBrlGtlDadwfML61vnI',
    appId: '1:426071864855:web:1072cbff3e358540778e52',
    messagingSenderId: '426071864855',
    projectId: 'backgroud-check-app',
    authDomain: 'backgroud-check-app.firebaseapp.com',
    storageBucket: 'backgroud-check-app.firebasestorage.app',
    measurementId: 'G-MY8T5MCG8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtPD9o_KutBRlTX7F7G6sYxsP8C58rfEA',
    appId: '1:426071864855:android:68f7f407b0ba420a778e52',
    messagingSenderId: '426071864855',
    projectId: 'backgroud-check-app',
    storageBucket: 'backgroud-check-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD26sCW3DisiM2sP05lpXexmQkoMxXuh44',
    appId: '1:426071864855:ios:f876043f2e5b122c778e52',
    messagingSenderId: '426071864855',
    projectId: 'backgroud-check-app',
    storageBucket: 'backgroud-check-app.firebasestorage.app',
    iosBundleId: 'com.example.backgroudCheckApp',
  );
}
